controllers:
<<<<<<< HEAD
    resource:
        path: ../src/Controller/
        namespace: App\Controller
=======
<<<<<<< HEAD
    resource:
        path: ../src/Controller/
        namespace: App\Controller
=======
    resource: ../src/Controller/
>>>>>>> 5e05068df1c86c1c41243b02f01d6d3a1fe7ae08
>>>>>>> 8ba3048163ae6bc316db3eb80ca3688bc7ea3320
    type: attribute
