# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
<<<<<<< HEAD

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
=======
parameters:
<<<<<<< HEAD
    blog_images_directory: '%kernel.project_dir%/public/uploads/blog_images'
=======
>>>>>>> 5e05068df1c86c1c41243b02f01d6d3a1fe7ae08
>>>>>>> 8ba3048163ae6bc316db3eb80ca3688bc7ea3320

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
<<<<<<< HEAD
            - '../src/Kernel.php'

    # Optional: Add any additional services here if needed
=======
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
>>>>>>> 8ba3048163ae6bc316db3eb80ca3688bc7ea3320
